name: Java CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: spring_homework
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd "pg_isready -U your_username" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Wait for PostgreSQL to start
        run: |
          until pg_isready -h localhost -p 5432 -U your_username; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Create database
        run: |
          psql -h localhost -U your_username -c "CREATE DATABASE spring_homework;" || echo "Database already exists."

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test -X -Duser.language=en -Duser.country=US
